name: Release Binary & OCI

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write        # Pour créer la release
  id-token: write        # Pour Cosign keyless (OIDC)
  attestations: write    # Pour GitHub attestations
  packages: write        # Pour publier sur ghcr.io

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Nécessaire pour GoReleaser changelog

      - name: Set up QEMU (for docker buildx multi-arch)
        uses: docker/setup-qemu-action@v3.7.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - name: Setup Go based on go.mod
        uses: actions/setup-go@v6.1.0
        with:
          go-version-file: go.mod

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.20.10

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest checksums.txt provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-checksums: dist/checksums.txt
            # dist/awesomecli_*_linux_amd64.tar.gz
            # dist/awesomecli_*_linux_arm64.tar.gz
            # dist/awesomecli_*_darwin_amd64.tar.gz
            # dist/awesomecli_*_darwin_arm64.tar.gz
            # dist/awesomecli_*_windows_amd64.zip
            # dist/awesomecli_*_windows_arm64.zip
      - name: Calculate artifact digests
        run: |
          cat dist/digests.txt     
      - name: Attest digests.txt provenance
        uses: actions/attest-build-provenance@v3
        # if: startsWith(github.ref, 'refs/tags/v') # snapshots won't push docker images
        with:
          subject-checksums: dist/digests.txt